### ISSUE TITLE
Implementacja algorytmów sortujących

### ISSUE THREAD

**Issue by DrozdzynskiDawid** [DrozdzynskiDawid/put_io_lab_SortingMadness#6]
Implementacja 6 algorytmów sortujących. Pomiar czasu sortowania.

**Comment by jjulkakulkaa** [comment]
Zaimplementowane: Bublle Sort, Insertion Sort, Selection Sort, Shell Sort, Heap Sort, Merge Sort

**Comment by jjulkakulkaa** [comment]
Zaimplementowane: Bublle Sort, Insertion Sort, Selection Sort, Shell Sort, Heap Sort, Merge Sort
